var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(static)/referral/referrals/new-referral/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__13q_5n4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_01uq7gm.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n1a69-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgvpt1._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_(static)_layout_tsx_0_qiife._.js")
R.c("server/chunks/ssr/app_(static)_referral_layout_tsx_0dxx0vq._.js")
R.c("server/chunks/ssr/0zjb_server_app_(static)_referral_referrals_new-referral_page_actions_0tthp...js")
R.m(94128)
module.exports=R.m(94128).exports
