// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/forgot-password" | "/forgot-password/forget-mail-sent" | "/forgot-password/reset-link-expired" | "/forgot-password/reset-password" | "/forgot-password/reset-successfully" | "/login" | "/privacy-policy" | "/referral-signup" | "/referral-signup/forgot-password" | "/referral-signup/forgot-password/forget-mail-sent" | "/referral-signup/forgot-password/reset-link-expired" | "/referral-signup/forgot-password/reset-password" | "/referral-signup/forgot-password/reset-successfully" | "/referral-signup/login" | "/referral-submission-external" | "/referral/messages" | "/referral/referrals/referral-request" | "/signup" | "/signup/profile-step" | "/terms-of-use" | "/user" | "/user/call" | "/user/channels" | "/user/dashboard" | "/user/messages" | "/user/profile" | "/user/recordings" | "/user/referrals/referral-request" | "/user/settings" | "/user/webinar"
type PageRoutes = never
type LayoutRoutes = "/" | "/referral" | "/referral-signup" | "/user"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/forgot-password": {}
  "/forgot-password/forget-mail-sent": {}
  "/forgot-password/reset-link-expired": {}
  "/forgot-password/reset-password": {}
  "/forgot-password/reset-successfully": {}
  "/login": {}
  "/privacy-policy": {}
  "/referral": {}
  "/referral-signup": {}
  "/referral-signup/forgot-password": {}
  "/referral-signup/forgot-password/forget-mail-sent": {}
  "/referral-signup/forgot-password/reset-link-expired": {}
  "/referral-signup/forgot-password/reset-password": {}
  "/referral-signup/forgot-password/reset-successfully": {}
  "/referral-signup/login": {}
  "/referral-submission-external": {}
  "/referral/messages": {}
  "/referral/referrals/referral-request": {}
  "/signup": {}
  "/signup/profile-step": {}
  "/terms-of-use": {}
  "/user": {}
  "/user/call": {}
  "/user/channels": {}
  "/user/dashboard": {}
  "/user/messages": {}
  "/user/profile": {}
  "/user/recordings": {}
  "/user/referrals/referral-request": {}
  "/user/settings": {}
  "/user/webinar": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/referral": never
  "/referral-signup": never
  "/user": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
