// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/(auth-flow)/forgot-password/forget-mail-sent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password/forget-mail-sent">> = Specific
  const handler = {} as typeof import("../../app/(auth-flow)/forgot-password/forget-mail-sent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth-flow)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/(auth-flow)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth-flow)/forgot-password/reset-link-expired/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password/reset-link-expired">> = Specific
  const handler = {} as typeof import("../../app/(auth-flow)/forgot-password/reset-link-expired/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth-flow)/forgot-password/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password/reset-password">> = Specific
  const handler = {} as typeof import("../../app/(auth-flow)/forgot-password/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth-flow)/forgot-password/reset-successfully/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password/reset-successfully">> = Specific
  const handler = {} as typeof import("../../app/(auth-flow)/forgot-password/reset-successfully/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth-flow)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(auth-flow)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth-flow)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/(auth-flow)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(auth-flow)/signup/profile-step/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup/profile-step">> = Specific
  const handler = {} as typeof import("../../app/(auth-flow)/signup/profile-step/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(static)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../app/(static)/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/referral-signup/forgot-password/forget-mail-sent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referral-signup/forgot-password/forget-mail-sent">> = Specific
  const handler = {} as typeof import("../../app/(static)/referral-signup/forgot-password/forget-mail-sent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/referral-signup/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referral-signup/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/(static)/referral-signup/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/referral-signup/forgot-password/reset-link-expired/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referral-signup/forgot-password/reset-link-expired">> = Specific
  const handler = {} as typeof import("../../app/(static)/referral-signup/forgot-password/reset-link-expired/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/referral-signup/forgot-password/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referral-signup/forgot-password/reset-password">> = Specific
  const handler = {} as typeof import("../../app/(static)/referral-signup/forgot-password/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/referral-signup/forgot-password/reset-successfully/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referral-signup/forgot-password/reset-successfully">> = Specific
  const handler = {} as typeof import("../../app/(static)/referral-signup/forgot-password/reset-successfully/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/referral-signup/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referral-signup/login">> = Specific
  const handler = {} as typeof import("../../app/(static)/referral-signup/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/referral-signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referral-signup">> = Specific
  const handler = {} as typeof import("../../app/(static)/referral-signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/referral-submission-external/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referral-submission-external">> = Specific
  const handler = {} as typeof import("../../app/(static)/referral-submission-external/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/referral/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referral/messages">> = Specific
  const handler = {} as typeof import("../../app/(static)/referral/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/referral/referrals/referral-request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referral/referrals/referral-request">> = Specific
  const handler = {} as typeof import("../../app/(static)/referral/referrals/referral-request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/terms-of-use/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-use">> = Specific
  const handler = {} as typeof import("../../app/(static)/terms-of-use/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/user/call/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/call">> = Specific
  const handler = {} as typeof import("../../app/user/call/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/user/channels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/channels">> = Specific
  const handler = {} as typeof import("../../app/user/channels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/user/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/dashboard">> = Specific
  const handler = {} as typeof import("../../app/user/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/user/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/messages">> = Specific
  const handler = {} as typeof import("../../app/user/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/user/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user">> = Specific
  const handler = {} as typeof import("../../app/user/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/user/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/profile">> = Specific
  const handler = {} as typeof import("../../app/user/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/user/recordings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/recordings">> = Specific
  const handler = {} as typeof import("../../app/user/recordings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/user/referrals/referral-request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/referrals/referral-request">> = Specific
  const handler = {} as typeof import("../../app/user/referrals/referral-request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/user/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/settings">> = Specific
  const handler = {} as typeof import("../../app/user/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/user/webinar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/webinar">> = Specific
  const handler = {} as typeof import("../../app/user/webinar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/(auth-flow)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(auth-flow)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(static)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/referral-signup/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/referral-signup">> = Specific
  const handler = {} as typeof import("../../app/(static)/referral-signup/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(static)/referral/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/referral">> = Specific
  const handler = {} as typeof import("../../app/(static)/referral/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/user/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/user">> = Specific
  const handler = {} as typeof import("../../app/user/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
