var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/user/referrals/referral-request/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__10_8qj2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0q109ds.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n1a69-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgvpt1._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_user_layout_tsx_0c6gj4h._.js")
R.c("server/chunks/ssr/_next-internal_server_app_user_referrals_referral-request_page_actions_0japqyr.js")
R.m(98647)
module.exports=R.m(98647).exports
