var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/(static)/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bgpa0q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0bu.h5x.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n1a69-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgvpt1._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_(static)_layout_tsx_0_qiife._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(static)_page_actions_0dvchf7.js")
R.m(69865)
module.exports=R.m(69865).exports
