var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(static)/referral/referrals/referral-request/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__01vgi..._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0fy3g6i.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n1a69-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgvpt1._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_(static)_layout_tsx_0_qiife._.js")
R.c("server/chunks/ssr/app_(static)_referral_layout_tsx_0dxx0vq._.js")
R.c("server/chunks/ssr/0zjb_server_app_(static)_referral_referrals_referral-request_page_actions_07qlw3g.js")
R.m(16986)
module.exports=R.m(16986).exports
