var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(static)/referral-signup/forgot-password/forget-mail-sent/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__01h6jh_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0uii.rf.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n1a69-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgvpt1._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_(static)_layout_tsx_0_qiife._.js")
R.c("server/chunks/ssr/app_(static)_referral-signup_layout_tsx_02wblj7._.js")
R.c("server/chunks/ssr/0ash_(static)_referral-signup_forgot-password_forget-mail-sent_page_actions_088u~2-.js")
R.m(19006)
module.exports=R.m(19006).exports
