var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/user/settings/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_~-z4k._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0no4l8z.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n1a69-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgvpt1._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_user_layout_tsx_0c6gj4h._.js")
R.c("server/chunks/ssr/_next-internal_server_app_user_settings_page_actions_0p~l20_.js")
R.m(11092)
module.exports=R.m(11092).exports
