var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth-flow)/forgot-password/reset-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__029hz_y._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0xoemh3.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n1a69-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgvpt1._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_(auth-flow)_layout_tsx_00nax~1._.js")
R.c("server/chunks/ssr/0zjb_server_app_(auth-flow)_forgot-password_reset-password_page_actions_128lmr3.js")
R.m(83615)
module.exports=R.m(83615).exports
