var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth-flow)/forgot-password/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e8mt1j._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0cz3410.js")
R.c("server/chunks/ssr/[root-of-the-server]__0n1a69-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zgvpt1._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_(auth-flow)_layout_tsx_00nax~1._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(auth-flow)_forgot-password_page_actions_0_~s~qi.js")
R.m(37776)
module.exports=R.m(37776).exports
